project:
  type: website

website:
  title: "Shifa Panjwani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  favicon: "favicon.ico"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
