project:
  type: website

website:
  title: "Shifa Panjwani"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
  favicon: "favicon.ico"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
