project:
  type: website

website:
  title: "Shifa Panjwani"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
    right:
      - icon: github
        href: https://github.com/shifapanjwanii
      - icon: linkedin
        href: "www.linkedin.com/in/shifapanjwanii"
      - icon: envelope
        href: "mailto:shifapanjwani30@gmail.com"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
