---
title: "Sample Analysis"
author: "Shifa Panjwani"
date: "2025-03-20"
categories: [tidymodels, tidyverse, ggplot2]
---

In the field of education, understanding the factors influencing student performance is critical for improving academic outcomes. This project aims to develop a predictive model to estimate students' Math scores using the [**Student Performance Prediction**](https://www.kaggle.com/datasets/spscientist/students-performance-in-exams?datasetId=74977) dataset. The dataset contains various demographic and academic features, including **gender**, **race/ethnicity**, **parental education level**, **lunch type**, **test preparation course completion**, as well as **reading and writing scores**.

The primary objective is to analyze how these factors contribute to Math performance and create an accurate machine learning model that can predict Math scores. By identifying the most significant predictors, the study will provide actionable insights for educators, policymakers, and academic institutions to implement targeted interventions and improve student outcomes.

Take a look at my [GitHub Repository](https://github.com/shifapanjwanii/stud_pred_R) to learn more about it!
